// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $blab.d3Object = (function() {

    function d3Object(id) {
      this.element = d3.select("#" + id);
      this.element.selectAll("svg").remove();
      this.obj = this.element.append("svg");
      this.initAxes();
    }

    d3Object.prototype.append = function(obj) {
      return this.obj.append(obj);
    };

    d3Object.prototype.initAxes = function() {};

    return d3Object;

  })();

  $blab.LineChart = (function(_super) {

    __extends(LineChart, _super);

    function LineChart(spec) {
      var click, r, _ref, _ref1, _ref2, _ref3, _ref4,
        _this = this;
      this.spec = spec;
      this.id = this.spec.id;
      this.container = $("#" + this.id);
      this.x0 = (_ref = this.spec.x0) != null ? _ref : 100;
      this.y0 = (_ref1 = this.spec.y0) != null ? _ref1 : 50;
      this.width = this.container.width() - this.x0 * 2;
      this.height = this.container.height() - this.y0 * 2;
      this.xLabel = (_ref2 = this.spec.xLabel) != null ? _ref2 : "";
      this.yLabel = (_ref3 = this.spec.yLabel) != null ? _ref3 : "";
      this.background = (_ref4 = this.spec.background) != null ? _ref4 : "#eee";
      LineChart.__super__.constructor.call(this, this.id);
      this.line = d3.svg.line().x(function(d) {
        return _this.xScale(d.x) + _this.x0;
      }).y(function(d) {
        return _this.yScale(d.y) + _this.y0;
      });
      r = this.append("rect").attr("width", this.width).attr("height", this.height).style("fill", this.background).attr("transform", "translate(" + this.x0 + ", " + this.y0 + ")");
      this.append("g").attr("class", "axis").attr("transform", "translate(" + this.x0 + ", " + (this.y0 + this.height) + ")").call(this.xAxis);
      this.append("text").attr("text-anchor", "center").attr("x", this.x0 + this.width / 2).attr("y", this.y0 + this.height + 40).text(this.xLabel);
      this.append("g").attr("class", "axis").attr("transform", "translate(" + this.x0 + ", " + this.y0 + ")").call(this.yAxis);
      this.append("text").attr("text-anchor", "middle").attr("x", this.x0 - 70).attr("y", this.y0 + this.height / 2).text(this.yLabel);
      if (this.spec.click != null) {
        click = function(coords) {
          var x, xm, y, ym;
          xm = coords[0], ym = coords[1];
          x = _this.xScale.invert(xm);
          y = _this.yScale.invert(ym);
          return _this.spec.click(x, y);
        };
        r.on("click", function() {
          return click(d3.mouse(this));
        });
      }
      this.path = null;
    }

    LineChart.prototype.plot = function(x, y, color, hold) {
      var data, foundNaN, idx, xp, yp, _i, _len;
      if (color == null) {
        color = "blue";
      }
      if (hold == null) {
        hold = false;
      }
      if (this.path && !hold) {
        this.path.remove();
      }
      data = (function() {
        var _i, _len, _results;
        _results = [];
        for (idx = _i = 0, _len = x.length; _i < _len; idx = ++_i) {
          xp = x[idx];
          _results.push({
            x: x[idx],
            y: y[idx]
          });
        }
        return _results;
      })();
      foundNaN = false;
      for (_i = 0, _len = y.length; _i < _len; _i++) {
        yp = y[_i];
        if (isNaN(yp) || Math.abs(yp) > 1e10) {
          foundNaN = true;
        }
      }
      if (foundNaN) {
        return;
      }
      return this.path = this.append("path").attr("d", this.line(data)).attr("stroke", color).attr("stroke-width", 2).attr("fill", "none");
    };

    LineChart.prototype.initAxes = function() {
      var _ref, _ref1, _ref2, _ref3;
      this.xScale = d3.scale.linear().domain((_ref = this.spec.xLim) != null ? _ref : [0, 1]).range([0, this.width]);
      this.xAxis = d3.svg.axis().scale(this.xScale).ticks((_ref1 = this.spec.xTicks) != null ? _ref1 : 10).orient("bottom");
      this.yScale = d3.scale.linear().domain((_ref2 = this.spec.yLim) != null ? _ref2 : [0, 1]).range([this.height, 0]);
      return this.yAxis = d3.svg.axis().scale(this.yScale).ticks((_ref3 = this.spec.yTicks) != null ? _ref3 : 10).orient("left");
    };

    return LineChart;

  })($blab.d3Object);

  $blab.stopAnimation = function() {
    if ($blab.animateId) {
      clearTimeout($blab.animateId);
    }
    return $blab.animateId = null;
  };

  $blab.animate = function(snapshotFunction, numSnapshots, delay) {
    var n, snapshot;
    if (delay == null) {
      delay = 10;
    }
    $blab.stopAnimation();
    n = 1;
    snapshot = function() {
      snapshotFunction();
      n++;
      if (n > numSnapshots) {
        return $blab.stopAnimation();
      }
    };
    return $blab.animateId = setInterval((function() {
      return snapshot();
    }), delay);
  };

}).call(this);
